# Setting of all environment things
# Note: on OSX /etc/zprofile renamed to /etc/zshenv because it incorrectly resets
# the path after it is updated here.

# Add to the path ensuring no duplicates
for x in ~/bin; do
  case ":$PATH:" in
    *":$x:"*) :;; # already there
    *) PATH="$x:$PATH";;
  esac
done

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_DEFAULT_OPTS="--inline-info"
export PIP_CONFIG_FILE=~/.config/pip/pip.conf
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/ripgreprc
