# Note: on OSX /etc/zprofile renamed to /etc/zshenv
# so that path not incorrectly overridden

# Set path
path=(
  $HOME/bin 
  $path
)

export LESS="-RM"
export LESSHISTFILE=-
export EDITOR=vim
export VISUAL=vim

export LSCOLORS=Gxfxcxdxbxegedabagacad

export HISTFILE=~/.local/share/zsh/history
export HISTSIZE=5000
export SAVEHIST=5000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_DEFAULT_OPTS="--inline-info"

export RIPGREP_CONFIG_PATH=~/.config/ripgrep/ripgreprc
export PIP_CONFIG_FILE=~/.config/pip/pip.conf

# Colourized man pages
# source: https://github.com/imkira/dotfiles/blob/master/.zsh/colored-man-pages.zsh
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;38;5;74m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[38;33;246m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[04;38;5;146m'
