#!/bin/bash

echo "Create .local directory structure..."
mkdir -p ~/.local/share/zsh ~/.local/share/vim ~/local/share/virtualenvs
mkdir -p ~/.local/share/cups

system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    else
        echo "Homebrew already installed. Skipping."
    fi

    if [ -f "~/.config/yadm/Brewfile" ]; then
        echo "Updating homebrew bundle..."
        brew bundle --verbose --file=~/.config/yadm/Brewfile
    else
        echo "Brewfile not found. Skipping brew installs."
    fi
fi

# Ensure the environment is setup
if [ -f "~/.zshrc" ]; then
    source ~/.zshrc
fi

# Set default config dir for Hammerspoon
if [ -d "/Applications/Hammerspoon.app" ]; then
  defaults write org.hammerspoon.Hammerspoon \
    MJConfigFile "$HOME/.config/hammerspoon/init.lua"
fi

# Get the latest vim version
if command -v make-vim >/dev/null 2>&1; then
    make-vim
fi

if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping vim..."
    vim '+PlugClean!' '+qall'
fi

if command -v pyenv >/dev/null 2>&1; then
    # Latest version of python that is not beta...
    python_version=$(pyenv install --list | grep -v - | grep -v b | tail -1)
    echo "Installing Python version $python_version..."
    pyenv install $python_version
    pyenv global  $python_version
    # Install poetry latest...
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    pip install spritemapper
fi

if command -v /usr/local/bin/gem >/dev/null 2>&1; then
    echo "Updating gem..."
    gem update --system
    gem install --force bundler
fi

if [ -f "~/bin/macos.sh" ]; then
    source ~/.config/yadm/macos.sh
fi
