yadm_tracked_recursively=(
    .local/bin
    .config
)

yadm_tracked_nonrecursively=(
    .
)

ignore_files_and_dirs=(
    .CFUserTextEncoding
    .DS_Store
    .vuescanrc
    .config/fish/fish_variables
    .config/gh
    .config/git/gitconfig.private
    .config/opencode
    .local/bin/yt-dlp
)
