gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#323232" # set to `default` to have no background colour

  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  showDivergenceFromBaseBranch: arrowAndNumber # or 'onlyArrow'
